services:
  worker:
    container_name: ratko
    build:
      context: .
    volumes:
      - worker:/data
    stop_signal: SIGINT
    restart: unless-stopped
    stdin_open: true
    tty: true
    init: true

volumes:
  worker:
